describe('Content of page', function() {
  it('Contains every element', function() {
    cy.visit('localhost:3000')
    cy.contains('Language Selector')
    cy.contains('History')
    cy.contains('User Input')
    cy.contains('Code Suggestion')
    cy.contains('Submit')
    cy.get('button').eq(0).contains('Javascript')
    cy.get('button').eq(1).contains('Ruby')
    cy.get('button').eq(2).contains('Python')
    cy.get('input#input')
    cy.get('input#output')
    cy.get('input#submit').contains('Submit')
  })
})
describe('Javascript', function() {
  it('Returns .reverse() when required', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('[1,2,3]')
    cy.get('input#output').type('[3,2,1]')
    cy.get('input#submit').click()
    cy.contains('javascript: [1,2,3] > [3,2,1] = reverse()')
  })
  it('can access elements in an array', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('[1,2,3,4]')
    cy.get('input#output').type('3')
    cy.get('input#submit').click()
    cy.contains('input[2]')
  })
  it('can sum an array', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('[10,20,30,40]')
    cy.get('input#output').type('100')
    cy.get('input#submit').click()
    cy.contains('javascript: [10,20,30,40] > 100 = reduce((a, b) => a + b)')
  })
  it('can convert a array to a string', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('[10,20,30,40]')
    cy.get('input#output').type('10,20,30,40')
    cy.get('input#submit').click()
    cy.contains('toString()')
  })
  it('can recognise an array of words', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('["hack", "the", "planet!"]')
    cy.get('input#output').type('hack the planet!')
    cy.get('input#submit').click()
    cy.contains("join(' ')")
  })
  it('can sort an array', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type('[5, 4, 8, 2]')
    cy.get('input#output').type('[2, 4, 5, 8]')
    cy.get('input#submit').click()
    cy.contains("sort()")
  })
  it('returns filter for null values', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type("['a', null,,4,null,true]")
    cy.get('input#output').type("['a', 4, true]")
    cy.get('input#submit').click()
    cy.contains("filter(e => e === 0 || e)")
  })
  it('returns map for multiplication', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(0).click()
    cy.get('input#input').type("[1, 2, 3]")
    cy.get('input#output').type("[13, 26, 39]")
    cy.get('input#submit').click()
    cy.contains('map(x => x * 13)')
  })
})
