describe('Ruby', function() {
  it('returns .reverse when required', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(1).click()
    cy.get('input#input').type("[1,2,3]")
    cy.get('input#output').type("[3,2,1]")
    cy.get('input#submit').click()
    cy.contains('.reverse')
  })
  it('returns .clear when required', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(1).click()
    cy.get('input#input').type("[1,2,3]")
    cy.get('input#output').type("[]")
    cy.get('input#submit').click()
    cy.contains('.clear')
  })
  it('returns .length', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(1).click()
    cy.get('input#input').type("[1,2,3]")
    cy.get('input#output').type("3")
    cy.get('input#submit').click()
    cy.contains('.length')
  })
  it('returns .compact when appropriate', function() {
    cy.visit('localhost:3000')
    cy.get('button').eq(1).click()
    cy.get('input#input').type('[1, 2, 3, null]')
    cy.get('input#output').type('[1,2,3]')
    cy.get('input#submit').click()
    cy.contains('.compact')
  })
})
